port:               4114
twilio_account_sid: fill-in-account-sid
twilio_auth_token:  fill-in-token

# This is used to encrypt sessions and next page URLs before serving them to
# the client.
#
# This should be a hex string that's exactly 64 bytes long. For example:
#
#   d7211b215341871968869ac50ef5302cc0ff1789fc88e0ac6e296ba36703edf8
#
# Don't reuse that key - you can generate a random key by running:
#
#   openssl rand -hex 32
#
# If no secret key is present, we'll generate one when the server starts.
# However, this means that sessions and any in-progress paging attempts will
# error when the server restarts.
#
# If a server key is present, but invalid, the server will crash.
secret_key: fill-in-key

# Set to "prod" in production. See bin/serve for an example.
realm:    local
user:     test
password: hymanrickover
# What timezone should we display for dates in the UI?
timezone: America/Los_Angeles

# What users type in their browser to reach your site
public_host: localhost:4114

# How many messages to fetch per page. A larger number will slow down load
# time. Defaults to 50.
messages_page_size: 10
